### ISSUE TITLE
Dissipation

### ISSUE THREAD

**Issue by WWIIWWIIWW** [AndreaDesan/pimpleTKEBudgetFoam#1]
Hi, 
got a feeling that the below line is incorrect in calculating resolved part of dissipation?
`volScalarField epsilonRes=-2*nuLam*(SRes && SRes);` //Instantaneous resolved dissipation rate

Shouldn't it be:
`volScalarField epsilonRes=-2*nuLam*(gradU && gradU);` ->I don't mind the constant -2*nuLam though.

Bests,
Kai.

**Comment by AndreaDesan** [comment]
Hi Kai, 

thanks for the message. I think the dissipation rate should be defined based on the gradient of the fluctuating velocity and not of the gradient of the velocity (as in your proposed modification). See the definition of epsilon [here](https://www.cfd-online.com/Wiki/Turbulence_dissipation_rate)  and note that the gradients are calculated with respect to u' (UPrime in the code) and not U. This is why SRes is defined as SRes = symm(fvc::grad(UPrime)) and not SRes = symm(fvc::grad(U)), basically because epsilon should be evaluated based on the resolved **fluctuating** rate of strain (and not on the resolved rate of strain). Hope this clarifies it.

Andrea

**Comment by WWIIWWIIWW** [comment]
Hi,
Thanks for the reply. There was a typo in my last message.
I mean, we should probably use
`volScalarField epsilonRes=-2*nuLam*(gradUPrime && gradUPrime);`

If symmetric part of grad(UPrime) is used, you will probably have something like gradU'*gradV' exist in the dissipation?

Kai/

**Comment by AndreaDesan** [comment]
Hi, 

I believe the cross products of the velocity gradient should be in the definition of the dissipation rate (see equation 3 [here](https://doi.org/10.1016/j.ces.2020.116133). I think the definition that is in the code is in agreement with the development shown in Equation 3 of that reference and also with a commonly used definition of the dissipation rate, i.e. 

epsilon = -2*nu* <S'_ij S'ij>

where S'_ij is the fluctuating rate of strain of tensor.

Andrea

**Comment by WWIIWWIIWW** [comment]
Thanks Andrea, I think I get your points.
The epsilon here is basically the sum of the dissipation for 9 Reynolds stress components. It is not directly linked to the kRes containing 3 diagonal components.

Kai.

**Comment by AndreaDesan** [comment]
Hi Kai, no problem - this was a useful sanity check.
I am going to close this issue.

Andrea
